### ISSUE TITLE
background is not black as shown in screenshots

### ISSUE THREAD

**Issue by QMaury** [gweithio/hotline-vim#3]
![image](https://user-images.githubusercontent.com/87496773/143389088-651008ee-d207-4988-91f7-f8549357a3c3.png)
background is a light grey instead of black. I'm not sure why. Maybe my terminal emulator or my .vimrc is wrong. What do you think?

**Comment by gweithio** [comment]
Have you tried setting these in your .vimrc, might help


```
set termguicolors
set t_Co=256
```

**Comment by QMaury** [comment]
tried. all it did was make Vim monochromatic
![image](https://user-images.githubusercontent.com/87496773/143390992-963104ee-7a9c-4b9f-91d9-7ba7d6d0e521.png)

**Comment by gweithio** [comment]
oh that's odd, what terminal have you got bud? I had a similar issue when I didn't set my term to xterm-256color

**Comment by QMaury** [comment]
st is my terminal.

I'm starting to think that it's working as intended and i'm just being silly. Although there are some things that look different from screenshots. After a bit more fiddling I got it to be like this
![image](https://user-images.githubusercontent.com/87496773/143391833-d10c4e0a-fb14-4ea0-b76b-3a421e6cff8d.png)

**Comment by gweithio** [comment]
Hmm, yeah. Could have a look at this, see if any fix your issue, but I imagine you've already found these.

https://stackoverflow.com/questions/61081231/st-vim-no-colors
https://github.com/vim/vim/issues/993#issuecomment-255651605

**Comment by QMaury** [comment]
No, I haven't seen these actually.
Let me take a look see...

**Comment by gweithio** [comment]
> No, I haven't seen these actually. Let me take a look see...

Cool cool, lemme know if that works, happy to add it to the README or too a wiki entry

**Comment by QMaury** [comment]
odd.
![image](https://user-images.githubusercontent.com/87496773/143392894-2fc69301-2778-44d1-8e68-107393767a84.png)
I think it might be something with my terminal colors and .Xresources.

I'm going to log off for now, I'll be happy to keep silly walkin around vimrc tomorrow.

**Comment by QMaury** [comment]
WINNAGE!
![image](https://user-images.githubusercontent.com/87496773/143393806-c0aca9f5-d5cb-4d37-8852-0e8061eb3400.png)
I got it workin.
Turns out that plugging it with vim-plug didnt work. I tried installing it manually && it works fine.
Thanks you for your help, sir. You were of great assistance. Good night. :)

**Comment by gweithio** [comment]
Thats odd, glad you got it working.
